### ISSUE TITLE
Example does'nt work

### ISSUE THREAD

**Issue by KolamInstitute** [dynmeth/RaphaelLayer#1]
Hi,
i've been trying to have the example working without success !

is there any tricks ?

before i link this plugin to the new leaflet version, i would like to see it working with the provided lib...

please help !

**Comment by adimitrov** [comment]
I believe this pull request will fix the example #2. You can check it out.

**Comment by dbhowell** [comment]
I've updated the example lib to use Leaflet 0.4.4, it should work now.
