### ISSUE TITLE
Compatibility issue with Leaflet's vector layer in overlayPane

### ISSUE THREAD

**Issue by ghost** [dynmeth/RaphaelLayer#6]
When I added L.Polyline and R.Marker two SVG containers - each for every layer - are put inside  `<div class="leaflet-overlay-pane"></div>` (called **overlayPane**) 
- file: [RaphaelLayer / src / layer / vector / Layer.Raphael.js](https://github.com/dynmeth/RaphaelLayer/blob/master/src/layer/vector/Layer.Raphael.js)
  - method `_updateRaphaelViewport` writes position changes (after e.g. drag&drop on map) to overlayPane
- file: [Leaflet / src / layer / vector / canvas / Path.Canvas.js](https://github.com/CloudMade/Leaflet/blob/master/src/layer/vector/canvas/Path.Canvas.js)
  - method `_updateSvgViewport` writes position changes to appropriate SVG container 

In this situation when I move my view, my polyline looses it's position.

![2013-01-06-211854_1920x1080_scrot](https://f.cloud.github.com/assets/1454301/46259/6a3fe05a-583e-11e2-9251-fdce18c43d30.png)

I have suppressed this issue by changing line 69 in _Layer.Raphael.js_ from `root = this._raphaelRoot;` to `root = this._raphaelRoot.firstChild;` in my project.

**Comment by dbhowell** [comment]
Hey Codename0, thanks for the contribution. By the way, your map looks great.

This is something I was hoping to fix in the next update, thanks!

**Comment by ghost** [comment]
Despite this solution I found, additional Raphael layer had really slowed down the browser, so I gave up on it. If only I haven't so large map (it fills browser window) and two tilelayers (they are already significantly slowing zooming).

**Comment by dbhowell** [comment]
Thanks for the update!
